<a href="https://colab.research.google.com/github/priyanshigarg17/datascience/blob/main/BODHAK_PANDAS_new_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
#context manager

In [ ]:
a = [1,7,2] #list
myvar = pd.Series(a)
print(myvar)

In [ ]:
print(myvar[1])

In [ ]:
a = [1,7,2]
myvar = pd.Series(a, index=["x", "y", "z"])
print(myvar)

In [ ]:
print(myvar["y"])

In [ ]:
print(myvar[1])

In [ ]:
#Key/Value Objects as Series
calories = {"day1": 420, "day2": 380, "day3":390}

myvar = pd.Series(calories)
print(myvar)

In [ ]:
#every key will be an index position
print(myvar['day2'])

In [ ]:
print(myvar[1])

In [ ]:
calories = {"day1": 420, "day2": 380, "day3":390}
myvar = pd.Series(calories, index=["day1", "day3","day4"])
print(myvar)

In [ ]:
calories = {"day1": 420, "day2": 380, "day3":390}
myvar = pd.Series(calories, index=[1, 2, 3,"day1"])
print(myvar)

In [ ]:
print(type(myvar))

### DataFrames: 2D

In [ ]:
data = {
    "calories": [420,380,390],
    "duration": [50,40,45]
}

df = pd.DataFrame(data)
print(df)

df.shape

In [ ]:
data = {
    "calories": [420,380,390],
    "duration": [50,40,45]
}

df = pd.DataFrame(data, index= ["day1", "day2", "day3"])
print(df)

In [ ]:
calories = {"day1": 420, "day2": 380, "day3":390}
myvar = pd.DataFrame(calories,index=[2])
print(myvar)

In [ ]:
#list into dataframe

lst = ["My", "name", "is", "nikhil", "garg"]

df = pd.DataFrame(lst)

df

In [ ]:
#list into dataframe

lst = ["My", "name", "is", "nikhil", "garg"]

df = pd.DataFrame(lst, columns = ["details"])

df

In [ ]:
#joining multiple lists
lst1 = ["My", "name", "is", "nikhil", "garg"]

lst2 = [2,4,8,9,6]

list(zip(lst1,lst2))#tuples inside list

In [ ]:
#convert multiple lists into dataframe

lst1 = ["My", "name", "is", "nikhil", "garg"]

lst2 = [2,4,8,9,6]

df = pd.DataFrame(list(zip(lst1,lst2)), columns = ["Details", "Val"])

df

In [ ]:
#conver a list of lists (multidimensional) into dataframe

lst = [['nikhil', 36], ["rupali", 30], ["deep", 28], ["prithvish", 35]]

df = pd.DataFrame(lst, columns=["Name", "Age"])

df

![image.png](attachment:image.png)

boat - Lifeboat (if survived)
body - Body number (if did not survive and body was recovered)

In [ ]:
import pandas as pd

#creating dataframe by the name of titanic
titanic = pd.read_csv("titanic.csv")
titanic #default print top 5 and the last 5 rows of the table

In [ ]:
titanic.shape

In [ ]:
titanic.head()
#5 top records

In [ ]:
titanic.tail(2)
#5 bottom most records

In [ ]:
#exploration of categorical columns
titanic["pclass"].unique()

In [ ]:
#summary of dataframe
titanic.info()

In [ ]:
#convert your dataframe into excel file
titanic.to_excel("titaniclpu.xlsx", sheet_name='passengers', index=False)

In [ ]:
titanic.head(2)

In [ ]:
#selection of columns and build a separate dataframe
ages = titanic[["age"]]
ages.head()

In [ ]:
type(ages)

In [ ]:
ages.shape

In [ ]:
age_sex = titanic[["age", "sex"]]
age_sex.head()

In [ ]:
age_sex.shape

In [ ]:
type(age_sex)

### Filter rows based on some condition

In [ ]:
#fetch records of passengers with age > 35, filtering rows based on some condition
titanic[titanic["age"] > 35]

In [ ]:
#conditional filter rows
#fetch passengers older than 35 (age)
#mention the condition on a specific column which you want to filter your rows
above_35 = titanic[titanic["age"] > 35]
above_35

In [ ]:
#passengers bw age 35 and 60

titanic[(titanic["age"] > 35) & (titanic["age"] < 60)]

In [ ]:
above_35 = titanic[(titanic["age"] > 35) & (titanic["age"] < 60)]
above_35

In [ ]:
above_35.reset_index().drop("index",axis=1)

In [ ]:
#passengers travelling in pclass 2 or 3; or operator

titanic[(titanic["pclass"] == 2) | (titanic["pclass"] == 3)]

In [ ]:
pclass_23 = titanic[(titanic['pclass']==2) | (titanic['pclass']==3)]
pclass_23

In [ ]:
#isin #pclass: 1, 2, 3 (categorical)
#Whether each element in the DataFrame is contained in value
#passenegers from cabin class 2 and 3

class_23 = titanic[titanic["pclass"].isin([2, 3])]
class_23

In [ ]:
titanic.info()

In [ ]:
titanic.dropna(subset="age")

In [ ]:
#notna #i want to work with passenger data for which age is known
#notna is a Boolean inverse of isna.
age_no_na = titanic[titanic["age"].notna()]
age_no_na

## Fetching rows and columns (Slicing)
1. fetch the rows and columns on the basis of index positions: iloc
2. fetch the rows and columns on the basis of labels (row as well as column labels): loc

In [ ]:
import pandas as pd

In [ ]:
brics = pd.read_csv('brics.csv', index_col=0)

In [ ]:
brics

In [ ]:
brics.shape

In [ ]:
brics.loc[["RU"]]#RU is the row label of second row

In [ ]:
brics.loc[["RU", "IN", "SA"]]

In [ ]:
#select both row and column, [row,column]
brics.loc[["RU", "IN", "SA"], ["country", "capital"]]

In [ ]:
brics.loc[:,["country", "capital"]]

In [ ]:
brics.loc[["BR","RU"], :]

In [ ]:
brics

In [ ]:
brics.iloc[[1]]

In [ ]:
brics.iloc[[1, 2, 4]]

In [ ]:
brics

In [ ]:
brics.iloc[[1, 2, 4], [1, 2]]

In [ ]:
brics.iloc[:, [1, 2]]

In [ ]:
brics.iloc[[3, 4], :]

In [ ]:
brics.iloc[2:5,:]
#rows from 3rd to 4th index position

In [ ]:
brics

In [ ]:
print(brics.duplicated())

In [ ]:
y = brics.drop_duplicates()
print(y)

In [ ]:
df = pd.DataFrame({
    "brand": ['yum', 'yum', 'ind'],
    "style": ['cup', 'cup', 'bottle']
})
df

In [ ]:
df.duplicated()

In [ ]:
df.drop_duplicates()

In [ ]:
df = pd.DataFrame({
    "brand": ['yum', 'yum', 'ind'],
    "style": ['cup', 'bottle', 'bottle']
})
df

In [ ]:
df.duplicated()

In [ ]:
df.duplicated(subset="brand")

In [ ]:
df.drop_duplicates(subset='brand')

In [ ]:
df.drop_duplicates(subset="brand").reset_index()

In [ ]:
brics

In [ ]:
brics.loc["BR", "country"] = "brasil"

In [ ]:
brics

In [ ]:
brics.iloc[0, 0]

In [ ]:
brics.loc["BR","country"]="Delhi"
brics

In [ ]:
brics

### How to create new columns derived from existing columns

In [ ]:
titanic = pd.read_csv("titanic.csv")

In [ ]:
titanic.head(2)

In [ ]:
titanic["fare"] = titanic["fare"] / 10
#no new column shall be generated

In [ ]:
titanic["modified_fare"] = titanic["fare"] / 10

In [ ]:
#lhs: name the new column you want to create
#rhs: select the existing column
titanic["modified_fare"] = titanic["fare"]/10

In [ ]:
titanic.head(2)

In [ ]:
titanic

In [ ]:
#renaming of columns
titanic_rename = titanic.rename(columns = {"sex":"gender", "name":"full name"})
titanic_rename.head(2)

In [ ]:
titanic

In [ ]:
titanic_rename.rename(columns = str.upper, inplace=True)
titanic_rename

## Statistical Explorations on Dataframe

In [ ]:
titanic.head(2)

Descriptive Statistics i.e. basic statistical metrics

10,15,20,30,45,50,63


Mean (average) = sum of all observations/no. of observations

Median = centre most value in a sorted data = 30

mode = most repeated item or most occuring: categorical columns

min

max

count = 7

In [ ]:
#summary statistics
titanic[["age", "fare"]].mean()

In [ ]:
titanic[["age", "fare"]].median()

In [ ]:
titanic[["age", "fare"]].describe()

In [ ]:
titanic["sex"].describe()

In [ ]:
titanic.agg({"age":["count","min","max","mean"], "fare": ["median","min","max"]})

In [ ]:
#make combinations
titanic.agg({'age': ["count",'min', 'max', 'mean'], 'fare': ['min', 'max', 'median']})

In [ ]:
titanic[["age","fare"]].describe()

In [ ]:
titanic[["age", "fare"]].mean()

In [ ]:
#What is the average age for male vs female titanic passengers?
#sex and age #mean
#aggregate statitics grouped the category: sex
#groupby

titanic[["sex", "age"]].groupby("sex").mean()

In [ ]:
titanic.groupby("sex") [["age"]].mean()

In [ ]:
#What is the mean ticket fare price for each of the cabin class combination?

titanic.groupby("pclass")[["fare"]].mean()

In [ ]:
#grouping multiple columns
#What is the mean ticket fare price for each of the sex and cabin class combination?
#fare #sex and pclass: categorical
titanic.groupby(["sex", "pclass"]) [["fare"]].mean()

In [ ]:
#What is the average fare and age for each of male and female class combination?
#sex #fare as well as age
titanic.groupby("sex") [["age", "fare"]].mean()

In [ ]:
titanic.groupby(["sex", "pclass"]) [["age", "fare"]].mean()

Combine the groupby and the agg method for selective metrics

In [ ]:
titanic.agg({"fare": ['mean', 'median'], "age": ['mean', 'min']})

In [ ]:
titanic.groupby(["sex", "pclass"]).agg({"fare": ['mean', 'median'], "age": ['mean', 'min']})

Identifying unique labels in categorical column

In [ ]:
import pandas as pd
titanic = pd.read_csv("titanic.csv")

In [ ]:
titanic["pclass"].unique()

In [ ]:
titanic["sex"].unique()

In [ ]:
#categorical columns #count
#what is the total number of passengers in each of the cabin class?

titanic["pclass"].value_counts()

In [ ]:
titanic["sex"].value_counts()

Sorting the dataframe

In [ ]:
#sort the data #age
titanic.sort_values(by="age", ascending=False).head()

In [ ]:
#sort on basis of categorical and continuous
titanic.sort_values(by=["pclass", "age"], ascending= False)

In [ ]:
titanic.sort_values(by=["age", "pclass"], ascending=False).head()

In [ ]:
#sort the data #age
titanic.sort_values(by="age", ascending=False).head()

In [ ]:
titanic.sort_values(by=["sex", "age"], ascending=False).head()

#### Replace Empty Values

Another way of dealing with empty cells is to insert a new value instead.

This way you do not have to delete entire rows just because of some empty cells.

The fillna() method allows us to replace empty cells with a value:

In [ ]:
#Replace NULL values with the number 130:
import pandas as pd

df = pd.read_csv('data.csv')

df

In [ ]:
df.info()

In [ ]:
df.isna().any()

In [ ]:
df.isna().sum()

In [ ]:
dfnew = df.dropna()

dfnew.shape

In [ ]:
dfnew.isna().sum()

Replace the missing value: constant, mean or median

In [ ]:
#using constant value to fill missing values
df["Calories"].fillna(420, inplace = True)

In [ ]:
df.isna().sum()

In [ ]:
df[df["Calories"] == 420]

In [ ]:
#Replace Using Mean, Median, or Mode
import pandas as pd

df = pd.read_csv('data.csv')

df.info()

In [ ]:
#computation of mean of the calories column
x = df["Calories"].mean()

print(x)

df["Calories"].fillna(x, inplace = True)

In [ ]:
df.isna().sum()

In [ ]:
df[df["Calories"] == x]

In [ ]:
#median
import pandas as pd

df = pd.read_csv('data.csv')

df.info()

In [ ]:
y = df["Calories"].median()

print(y)

df["Calories"].fillna(y, inplace = True)

In [ ]:
df[df["Calories"] == 318.6]

In [ ]:
df["Calories"].mode()[0]

np.float64(300.0)

In [ ]:
#mode on categorical columns
import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].mode()[0]

df["Calories"].fillna(x, inplace = True)

/tmp/ipython-input-25-3517734203.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Calories"].fillna(x, inplace = True)

In [ ]:
x

#### Cleaning Data of Wrong Format

Cells with data of wrong format can make it difficult, or even impossible, to analyze data.

To fix it, you have two options: remove the rows, or convert all cells in the columns into the same format.

In [ ]:
#data column to datetime format
import pandas as pd

df = pd.read_csv('dirtydata.csv')

df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [ ]:
df['Date'] = pd.to_datetime(df['Date'],format="mixed")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     datetime64[ns]
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(3)
memory usage: 1.4 KB

In [ ]:
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [ ]:
df["Date"].fillna('2020-12-22',inplace=True)

/tmp/ipython-input-30-3921050731.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Date"].fillna('2020-12-22',inplace=True)

In [ ]:
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45 2020-12-22    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

As you can see from the result, the date in row 26 was fixed, but the empty date in row 22 got a NaT (Not a Time) value, in other words an empty value. One way to deal with empty values is simply removing the entire row.

In [ ]:
df.dropna()

In [ ]:
#emove rows with a NULL value in the "Date" column:
df.dropna(subset=['Date'], inplace = True)
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

### Concatenating two dataframes

In [ ]:
north_america = pd.read_csv("north_america.csv")
north_america

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
0,Canada,1779.0,1771.0,1754.0,1740.0,1760.0,1747,1745.0,1741.0,1735,1701.0,1703.0
1,Mexico,2311.2,2285.2,2271.2,2276.5,2270.6,2281,2280.6,2261.4,2258,2250.2,2242.4
2,USA,1836.0,1814.0,1810.0,1800.0,1802.0,1799,1800.0,1798.0,1792,1767.0,1778.0

In [ ]:
south_america = pd.read_csv("south_america.csv")
south_america

  Country  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009    2010
0   Chile  2263  2242  2250  2235  2232  2157  2165  2128  2095  2074  2069.6

In [ ]:
americas = pd.concat([north_america, south_america], axis=0)
americas

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
0,Canada,1779.0,1771.0,1754.0,1740.0,1760.0,1747,1745.0,1741.0,1735,1701.0,1703.0
1,Mexico,2311.2,2285.2,2271.2,2276.5,2270.6,2281,2280.6,2261.4,2258,2250.2,2242.4
2,USA,1836.0,1814.0,1810.0,1800.0,1802.0,1799,1800.0,1798.0,1792,1767.0,1778.0
0,Chile,2263.0,2242.0,2250.0,2235.0,2232.0,2157,2165.0,2128.0,2095,2074.0,2069.6

In [ ]:
americas = pd.concat([north_america, south_america], axis=1)
americas

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
0,Canada,1779.0,1771.0,1754.0,1740.0,1760.0,1747,1745.0,1741.0,1735,...,2242.0,2250.0,2235.0,2232.0,2157.0,2165.0,2128.0,2095.0,2074.0,2069.6
1,Mexico,2311.2,2285.2,2271.2,2276.5,2270.6,2281,2280.6,2261.4,2258,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USA,1836.0,1814.0,1810.0,1800.0,1802.0,1799,1800.0,1798.0,1792,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Adding Columns

In [ ]:
# Import pandas package
import pandas as pd

# Define a dictionary containing Students data
data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc']}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

df

     Name  Height Qualification
0     Jai     5.1           Msc
1  Princi     6.2            MA
2  Gaurav     5.1           Msc
3    Anuj     5.2           Msc

In [ ]:
# Declare a list that is to be converted into a column
address = ['Delhi', 'Bangalore', 'Chennai', 'Patna']

# Using 'Address' as the column name
# and equating it to the list
df['City'] = address

# Observe the result
df

     Name  Height Qualification       City
0     Jai     5.1           Msc      Delhi
1  Princi     6.2            MA  Bangalore
2  Gaurav     5.1           Msc    Chennai
3    Anuj     5.2           Msc      Patna

In [ ]:
# Import pandas package
import pandas as pd

# Define a dictionary containing Students data
data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc']}

# Define a dictionary mapping names to cities
address = {'Jai': 'Delhi', 'Princi': 'Bangalore',
           'Gaurav': 'Patna', 'Anuj': 'Chennai'}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

# Use map() to assign cities based on the Name column
df['City'] = df['Name'].map(address)

# Observe the output
print(df)

     Name  Height Qualification       City
0     Jai     5.1           Msc      Delhi
1  Princi     6.2            MA  Bangalore
2  Gaurav     5.1           Msc      Patna
3    Anuj     5.2           Msc    Chennai

In [ ]:
# Import pandas package
import pandas as pd

# Define a dictionary containing Students data
data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc']}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)
df

     Name  Height Qualification
0     Jai     5.1           Msc
1  Princi     6.2            MA
2  Gaurav     5.1           Msc
3    Anuj     5.2           Msc

In [ ]:
# Using DataFrame.insert() to add a column
df.insert(2, "Age", [21, 23, 24, 21], True) #allow duplicates

# Observe the result
df

     Name  Height  Age Qualification
0     Jai     5.1   21           Msc
1  Princi     6.2   23            MA
2  Gaurav     5.1   24           Msc
3    Anuj     5.2   21           Msc

### Reindexing

In [ ]:
# import numpy and pandas module
import pandas as pd
import numpy as np

column = ['a', 'b', 'c', 'd', 'e']
index = ['A', 'B', 'C', 'D', 'E']

# create a dataframe of random values of array
df1 = pd.DataFrame(np.random.rand(5, 5),
        columns = column, index = index)

df1

          a         b         c         d         e
A  0.860478  0.450458  0.694777  0.941500  0.677853
B  0.462952  0.725098  0.022615  0.938248  0.813685
C  0.550617  0.258526  0.053454  0.179023  0.784700
D  0.896156  0.888615  0.703605  0.536959  0.913876
E  0.885884  0.830490  0.531697  0.256803  0.729273

In [ ]:
# create the new index for rows
new_index =['E', 'A', 'B', 'C', 'D']

print(df1.reindex(new_index)) #axis=0 is default

          a         b         c         d         e
E  0.885884  0.830490  0.531697  0.256803  0.729273
A  0.860478  0.450458  0.694777  0.941500  0.677853
B  0.462952  0.725098  0.022615  0.938248  0.813685
C  0.550617  0.258526  0.053454  0.179023  0.784700
D  0.896156  0.888615  0.703605  0.536959  0.913876

In [ ]:

# import numpy and pandas module
import pandas as pd
import numpy as np

column=['a','b','c','d','e']
index=['A','B','C','D','E']

#create a dataframe of random values of array
df1 = pd.DataFrame(np.random.rand(5,5),
           columns=column, index=index)
df1

          a         b         c         d         e
A  0.950426  0.218146  0.054963  0.249504  0.088968
B  0.865535  0.121016  0.229896  0.083128  0.603047
C  0.486083  0.854548  0.395444  0.510531  0.910651
D  0.283987  0.916138  0.965820  0.281974  0.910981
E  0.497717  0.756165  0.128934  0.978658  0.198263

In [ ]:
column=['e','a','b','d','c']

# create the new index for columns
print(df1.reindex(column, axis=1))

          e         a         b         d         c
A  0.088968  0.950426  0.218146  0.249504  0.054963
B  0.603047  0.865535  0.121016  0.083128  0.229896
C  0.910651  0.486083  0.854548  0.510531  0.395444
D  0.910981  0.283987  0.916138  0.281974  0.965820
E  0.198263  0.497717  0.756165  0.978658  0.128934

### Merging two data frames

In [ ]:
import pandas as pd

In [ ]:
player = ['Player1','Player2','Player3']
point = [8,9,6]
title = ['Game1','Game2','Game3']
df1 = pd.DataFrame({'Player':player, 'Points': point, 'Title': title})
df1#left table

In [ ]:
player = ['Player1', 'Player5', 'Player6']
power = ['Punch', 'kick', 'Elbow']
title = ['Game1', 'Game5','Game6']
df2 = pd.DataFrame({'Player': player, 'Power': power, 'Title': title})
df2 #right table

In [ ]:
df1.merge(df2) # by default it is inner

In [ ]:
df1.merge(df2, on='Player', how='outer')
#all records from both tables

In [ ]:
#left merge
#all tables would be merged together but bcoz player 2&3 aren't available in 2nd table we have NaN against them
df1.merge(df2, on='Player', how='left')

In [ ]:
#right merge
df1.merge(df2, on='Player', how='right')

### Join two dataframes

Using join method, allows you to merge on the basis of index positions instead of column name

In [ ]:
player = ['Player1','Player2','Player3']
point = [8,9,6]
title = ['Game1','Game2','Game3']
df3 = pd.DataFrame({'Player':player, 'Points': point, 'Title': title}, index=['L1','L2','L3'])
df3

In [ ]:
player = ['Player1', 'Player5', 'Player6']
power = ['Punch', 'Kick', 'Elbow']
title = ['Game1', 'Game5', 'Game6']
df4 = pd.DataFrame({'Players':player, 'Power':power, 'Titles':title}, index=['L2','L3','L4'])
df4

In [ ]:
#inner join
df3.join(df4, how='inner')

In [ ]:
#left join
df3.join(df4, how='right')

In [ ]:
#left join
df3.join(df4, how='left')

In [ ]:
#outer join
df3.join(df4, how='outer')

In [ ]:
### merging multiple dataframes
player = ['Player1','Player2','Player3', 'Player4']
score = [88,92,63, 22]
df1 = pd.DataFrame({'Player':player, 'Scores': score})
print(df1)

player = ['Player1','Player2','Player4']
wicket = [0,1,5]
df2 = pd.DataFrame({'Player':player, 'Wickets': wicket})
print(df2)

player = ['Player4','Player2','Player3']
catches = [0, 2, 1]
df3 = pd.DataFrame({'Player':player, 'Catch': catches})
print(df3)

player = ['Player4','Player5','Player3']
fifty = [0, 2, 1]
df4 = pd.DataFrame({'Player':player, 'Fifty': fifty})
print(df4)

1,2,4,5,6,4,7,8

In [ ]:
from functools import reduce
data_frames = [df1, df2, df3, df4]
df_merged = reduce(lambda  a,b: pd.merge(a, b ,on=['Player'],
                                            how='outer'), data_frames)

df_merged

### Time Stamp

The program below converts a datetime object containing current date and time to different string formats.

In [ ]:
from datetime import datetime
from zoneinfo import ZoneInfo

now = datetime.now(ZoneInfo("Asia/Kolkata")) # current date and time
print(now)

2025-07-03 21:46:24.835138+05:30

In [ ]:
from datetime import datetime

now = datetime.now(ZoneInfo("Asia/Kolkata")) # current date and time
print(now)

year = now.strftime("%Y")
print("year:", year)

month = now.strftime("%m")
print("month:", month)

day = now.strftime("%d")
print("day:", day)

time = now.strftime("%H:%M:%S")
print("time:", time)

date_time = now.strftime("%m/%d/%Y, %H:%M:%S")
print("date and time:",date_time)

2025-07-03 21:48:14.138331+05:30
year: 2025
month: 07
day: 03
time: 21:48:14
date and time: 07/03/2025, 21:48:14

Here, year, day, time and date_time are strings, whereas now is a datetime object.

In the above program, %Y, %m, %d etc. are format codes. The strftime() method takes one or more format codes as an argument and returns a formatted string based on it.

### Creating string from a timestamp

In [ ]:

timestamp = 1528797322
date_time = datetime.fromtimestamp(timestamp)
date_time

datetime.datetime(2018, 6, 12, 9, 55, 22)

In [ ]:
from datetime import datetime

timestamp = 1528797322
date_time = datetime.fromtimestamp(timestamp)

print("Date time object:", date_time)

d = date_time.strftime("%m/%d/%Y, %H:%M:%S")
print("Output 2:", d)

d = date_time.strftime("%d %b, %Y")
print("Output 3:", d)

d = date_time.strftime("%d %B, %Y")
print("Output 4:", d)

d = date_time.strftime("%I%p")
print("Output 5:", d)

Date time object: 2018-06-12 09:55:22
Output 2: 06/12/2018, 09:55:22
Output 3: 12 Jun, 2018
Output 4: 12 June, 2018
Output 5: 09AM

In [ ]:
#locale based
from datetime import datetime

timestamp = 1528797322
date_time = datetime.fromtimestamp(timestamp)

d = date_time.strftime("%c")
print("Output 1:", d)

d = date_time.strftime("%x")
print("Output 2:", d)

d = date_time.strftime("%X")
print("Output 3:", d)

Output 1: Tue Jun 12 09:55:22 2018
Output 2: 06/12/18
Output 3: 09:55:22